---
- name: Testing andrewrothstein.nomad
  hosts: all
  tasks:
    - name: Installing andrewrothstein.nomad
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'nomad --version'
      ansible.builtin.command: /usr/local/bin/nomad --version
      changed_when: false
      register: nomad_test_output
    - name: Output from 'nomad --version'
      ansible.builtin.debug:
        msg: '{{ nomad_test_output.stdout }}'
