---
- name: installing nomad binaries
  include_role:
    name: andrewrothstein.hashi
  vars:
    hashi_apps:
      - name: '{{ nomad_app.name | default("nomad") }}'
        ver: '{{ nomad_app.ver | default(nomad_ver) }}'
        meta: '{{ nomad_app.meta | default("") }}'
